base:
  build: .
  ports:
    - "9000:9000"    
  container_name: control-tower
mongo:
  image: mongo
  container_name: control-tower-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/mongodb:/data/db
  restart: always
