base:
  build: .
  ports:
    - "9000:9000"
  container_name: control-tower
mongo:
  image: mongo
  container_name: control-tower-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    - $HOME/docker/control-tower/mongodb:/data/db
  restart: always

redis:
  image: redis
  container_name: control-tower-redis
  ports:
    - "6379:6379"
  restart: always
